// Generated by CoffeeScript 1.10.0
(function() {
  describe('Automaton', function() {
    beforeEach(function() {
      this.grid_container = jQuery('<div/>');
      return this.grid = new Grid(this.grid_container, {
        height: 2,
        width: 2
      });
    });
    it('accepts a grid and a rule and applies the rule to the grid', function() {
      var automaton, rule;
      rule = function(x, y, grid) {
        return x === y;
      };
      automaton = new Automaton(this.grid, rule);
      spyOn(this.grid, 'turn_on');
      spyOn(this.grid, 'turn_off');
      automaton.step();
      expect(this.grid.turn_on).toHaveBeenCalledWith({
        x: 0,
        y: 0
      });
      expect(this.grid.turn_on).toHaveBeenCalledWith({
        x: 1,
        y: 1
      });
      expect(this.grid.turn_off).toHaveBeenCalledWith({
        x: 0,
        y: 1
      });
      return expect(this.grid.turn_off).toHaveBeenCalledWith({
        x: 1,
        y: 0
      });
    });
    return it('makes all moves simultaneously', function() {
      var automaton, rule;
      rule = function(x, y, grid) {
        if ((x === y && y === 0)) {
          return true;
        }
        if (y > 0) {
          return false;
        }
        if (!grid.is_on({
          x: x - 1,
          y: y
        })) {
          return true;
        }
      };
      automaton = new Automaton(this.grid, rule);
      spyOn(this.grid, 'turn_on').and.callThrough();
      automaton.step();
      expect(this.grid.turn_on).toHaveBeenCalledWith({
        x: 0,
        y: 0
      });
      return expect(this.grid.turn_on).toHaveBeenCalledWith({
        x: 1,
        y: 0
      });
    });
  });

}).call(this);
