// Generated by CoffeeScript 1.10.0
(function() {
  describe('Example', function() {
    return it('should be deleted', function() {
      return expect(true).toEqual(false);
    });
  });

}).call(this);
