// Generated by CoffeeScript 1.10.0
(function() {
  describe('Grid', function() {
    beforeEach(function() {
      return this.grid_container = jQuery('<div/>');
    });
    it('creates a grid in the given container', function() {
      var grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10
      });
      grid_table = this.grid_container.children('table');
      expect(grid_table.length).toEqual(1);
      expect(grid_table.children('tr').length).toEqual(10);
      return _.each(grid_table.children('tr'), function(row) {
        return expect(jQuery(row).children('td').length).toEqual(10);
      });
    });
    it('labels each cell in the grid', function() {
      var grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10
      });
      grid_table = this.grid_container.children('table');
      return _.times(10, function(row_number) {
        return _.times(10, function(cell_number) {
          var cell;
          cell = grid_table.find(".row" + row_number + "#cell" + cell_number);
          expect(cell.length).toEqual(1);
          expect(cell.data('coordinates')).toEqual({
            x: cell_number,
            y: row_number
          });
          return expect(cell.attr('data-state')).toEqual('0');
        });
      });
    });
    it('can turn on a given cell', function() {
      var cell, grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10
      });
      grid_table = this.grid_container.children('table');
      grid.turn_on({
        x: 7,
        y: 3
      });
      cell = grid_table.find('.row3#cell7');
      return expect(cell.attr('data-state')).toEqual('1');
    });
    it('can turn off a given cell', function() {
      var grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10
      });
      grid_table = this.grid_container.children('table');
      grid.turn_on({
        x: 7,
        y: 3
      });
      grid.turn_off({
        x: 7,
        y: 3
      });
      return expect(grid_table.find('.row3#cell7').attr('data-state')).toEqual('0');
    });
    it('can toggle a given cell', function() {
      var grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10
      });
      grid_table = this.grid_container.children('table');
      grid.toggle({
        x: 4,
        y: 8
      });
      expect(grid_table.find('.row8#cell4').attr('data-state')).toEqual('1');
      grid.toggle({
        x: 4,
        y: 8
      });
      return expect(grid_table.find('.row8#cell4').attr('data-state')).toEqual('0');
    });
    it('can set a given cell value', function() {
      var grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10
      });
      grid_table = this.grid_container.children('table');
      grid.set({
        x: 4,
        y: 8
      }, 1);
      expect(grid_table.find('.row8#cell4').attr('data-state')).toEqual('1');
      grid.set({
        x: 4,
        y: 8
      }, 0);
      return expect(grid_table.find('.row8#cell4').attr('data-state')).toEqual('0');
    });
    it('can be made interactive', function() {
      var cell, grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10,
        interactive: true
      });
      grid_table = this.grid_container.children('table');
      cell = grid_table.find('.row9#cell2');
      cell.click();
      expect(cell.attr('data-state')).toEqual('1');
      cell.click();
      return expect(cell.attr('data-state')).toEqual('0');
    });
    it('can tell if a given cell is active', function() {
      var grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10,
        interactive: true
      });
      grid_table = this.grid_container.children('table');
      grid.turn_on({
        x: 4,
        y: 5
      });
      expect(grid.is_on({
        x: 4,
        y: 5
      })).toEqual(true);
      grid.turn_off({
        x: 4,
        y: 5
      });
      return expect(grid.is_on({
        x: 4,
        y: 5
      })).toEqual(false);
    });
    it('can read the state of a given cell', function() {
      var grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10,
        interactive: true
      });
      grid_table = this.grid_container.children('table');
      grid.set({
        x: 4,
        y: 5
      }, 1);
      expect(grid.state({
        x: 4,
        y: 5
      })).toEqual(1);
      grid.set({
        x: 4,
        y: 5
      }, 0);
      return expect(grid.state({
        x: 4,
        y: 5
      })).toEqual(0);
    });
    return it('can be initialized with a number of possible states and cycle through them', function() {
      var coordinates, grid, grid_table;
      grid = new Grid(this.grid_container, {
        height: 10,
        width: 10,
        states: 3
      });
      grid_table = this.grid_container.children('table');
      coordinates = {
        x: 2,
        y: 7
      };
      expect(grid.state(coordinates)).toEqual(0);
      grid.toggle(coordinates);
      expect(grid.state(coordinates)).toEqual(1);
      grid.toggle(coordinates);
      expect(grid.state(coordinates)).toEqual(2);
      grid.toggle(coordinates);
      return expect(grid.state(coordinates)).toEqual(0);
    });
  });

}).call(this);
