// Generated by CoffeeScript 1.10.0
(function() {
  this.Grid = (function() {
    function Grid(container, arg) {
      this.container = container;
      this.height = arg.height, this.width = arg.width;
      this._add_grid_to_container();
    }

    Grid.prototype.turn_on = function(coordinates) {
      return this._grid_cell(coordinates).addClass('active');
    };

    Grid.prototype.turn_off = function(coordinates) {
      return this._grid_cell(coordinates).removeClass('active');
    };

    Grid.prototype.toggle = function(coordinates) {
      return this._grid_cell(coordinates).toggleClass('active');
    };

    Grid.prototype._grid_cell = function(arg) {
      var x, y;
      x = arg.x, y = arg.y;
      return this.grid.find(".row" + y + "#cell" + x);
    };

    Grid.prototype._add_grid_to_container = function() {
      return this.container.append(this._grid());
    };

    Grid.prototype._grid = function() {
      this.grid = jQuery('<table/>');
      _.times(this.height, (function(_this) {
        return function(row_number) {
          return _this.grid.append(_this._row(row_number));
        };
      })(this));
      return this.grid;
    };

    Grid.prototype._row = function(row_number) {
      var row;
      row = jQuery('<tr/>');
      return _.times(this.width, (function(_this) {
        return function(cell_number) {
          return row.append(_this._cell(row_number, cell_number));
        };
      })(this));
    };

    Grid.prototype._cell = function(row_number, cell_number) {
      return jQuery('<td/>', {
        "class": "row" + row_number,
        id: "cell" + cell_number
      });
    };

    return Grid;

  })();

}).call(this);
