// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var grid_container;
    grid_container = jQuery('<div/>', {
      id: 'grid_container'
    });
    jQuery('body').append(grid_container);
    return window.grid = new Grid(grid_container, {
      height: 20,
      width: 20,
      interactive: true
    });
  });

}).call(this);
