// Generated by CoffeeScript 1.10.0
(function() {
  this.rules = {
    conways_game_of_life: {
      name: "Conway's Game of Life",
      states: 2,
      colors: ['inherit', '#E8107C'],
      rule: function(x, y, grid) {
        var east, north, northeast, northwest, number_of_live_neighbors, self, south, southeast, southwest, west;
        self = grid.is_on({
          x: x,
          y: y
        });
        northwest = grid.is_on({
          x: x - 1,
          y: y - 1
        });
        north = grid.is_on({
          x: x,
          y: y - 1
        });
        northeast = grid.is_on({
          x: x + 1,
          y: y - 1
        });
        west = grid.is_on({
          x: x - 1,
          y: y
        });
        east = grid.is_on({
          x: x + 1,
          y: y
        });
        southwest = grid.is_on({
          x: x - 1,
          y: y + 1
        });
        south = grid.is_on({
          x: x,
          y: y + 1
        });
        southeast = grid.is_on({
          x: x + 1,
          y: y + 1
        });
        number_of_live_neighbors = _.compact([northwest, north, northeast, west, east, southwest, south, southeast]).length;
        switch (false) {
          case number_of_live_neighbors !== 3:
            return true;
          case !(number_of_live_neighbors < 2):
            return false;
          case !(number_of_live_neighbors > 3):
            return false;
          default:
            return self;
        }
      }
    },
    fire_propagation: {
      name: 'Fire Propagation',
      states: 7,
      colors: ['inherit', 'black', '#ED6509', '#ED6509', '#ED6509', '#ED6509', '#632E0A'],
      rule: function(x, y, grid) {
        var BURNED_OUT, FIREBREAK, FIRESTART, NORMAL, chance_of_catching_fire, east, neighbors, north, northeast, northwest, number_of_burning_neighbors, self, south, southeast, southwest, west;
        NORMAL = 0;
        FIREBREAK = 1;
        FIRESTART = 2;
        BURNED_OUT = 6;
        self = grid.state({
          x: x,
          y: y
        });
        if (self === FIREBREAK) {
          return FIREBREAK;
        }
        if (self > FIREBREAK) {
          return Math.min(self + 1, BURNED_OUT);
        }
        northwest = grid.state({
          x: x - 1,
          y: y - 1
        });
        north = grid.state({
          x: x,
          y: y - 1
        });
        northeast = grid.state({
          x: x + 1,
          y: y - 1
        });
        west = grid.state({
          x: x - 1,
          y: y
        });
        east = grid.state({
          x: x + 1,
          y: y
        });
        southwest = grid.state({
          x: x - 1,
          y: y + 1
        });
        south = grid.state({
          x: x,
          y: y + 1
        });
        southeast = grid.state({
          x: x + 1,
          y: y + 1
        });
        neighbors = [northwest, north, northeast, west, east, southwest, south, southeast];
        number_of_burning_neighbors = _.size(_.filter(neighbors, function(neighbor) {
          return neighbor > FIREBREAK && neighbor < BURNED_OUT;
        }));
        chance_of_catching_fire = number_of_burning_neighbors * 1 / 8;
        if (Math.random() < chance_of_catching_fire) {
          return FIRESTART;
        }
        return self;
      }
    }
  };

}).call(this);
